name: Deploy

on:
  # set triggers here, like on push or on release
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - name: install dependencies
        run: npm ci # or yarn install --frozen-lockfile
      - name: build
        run: npm run build # or yarn build
      - name: push to gh-pages
        run: |
          cd dist
          git config --global init.defaultBranch main
          git init
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m 'deploy'
          git push -f https://github-actions[bot]:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY.git main:gh-pages
